// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EchoService.proto

package com.example.grpc;

public interface EchoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.EchoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string from = 2;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();
}
