// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EchoService.proto

package com.example.grpc;

public final class EchoServiceOuterClass {
  private EchoServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_EchoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_EchoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_EchoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_EchoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021EchoService.proto\022\020com.example.grpc\"\036\n" +
      "\013EchoRequest\022\017\n\007message\030\001 \001(\t\"-\n\014EchoRes" +
      "ponse\022\017\n\007message\030\001 \001(\t\022\014\n\004from\030\002 \001(\t2T\n\013" +
      "EchoService\022E\n\004echo\022\035.com.example.grpc.E" +
      "choRequest\032\036.com.example.grpc.EchoRespon" +
      "seB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_EchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_EchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_EchoRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_example_grpc_EchoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_EchoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_EchoResponse_descriptor,
        new java.lang.String[] { "Message", "From", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
