apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: grpc-echo-client
  name: grpc-echo-client
spec:
  replicas: 2
  selector:
    matchLabels:
      run: grpc-echo-client
  template:
    metadata:
      labels:
        run: grpc-echo-client
    spec:
      containers:
      - name: grpc-echo-client
        image: dhirajnair/grpc-echo-client
        env:
        - name: ECHO_SERVICE_HOST
          value: grpc-echo-server
        - name: ECHO_SERVICE_PORT
          value: "8080"
        - name: ECHO_CLIENT_THREADS
          value: "5"